Lib fork
Qbox-project/qbx_recyclejob pull request #13
Opened 2024-02-09 19:32 UTC by StrixLuca

It functions

i adapted it for qbx lib

But that bug
that you have to restart the script in game for it to work

It's still there

2024-02-09 23:48 UTC, solareon requested changes
Please convert ar/cs/es/fr since we had them before.

2024-02-11 23:53 UTC, BerkieBb commented on client/main.lua
> +
so much empty space which doesn't need to be here

2024-02-11 23:53 UTC, BerkieBb commented on fxmanifest.lua
> +   '@qbx_core/modules/lib.lua',
indentation is off here

2024-02-11 23:53 UTC, BerkieBb commented on fxmanifest.lua
> -
put this space back

2024-02-13 11:28 UTC, solareon approved these changes

2024-02-13 12:17 UTC, BerkieBb approved these changes

2024-02-13 13:27 UTC, merged